"""
SQLAlchemy ORM model for the api_audit_log table.

The DDL is also expressed in migrations/001_initial.sql — this model must
stay in sync with it.
"""
from __future__ import annotations

import uuid

from sqlalchemy import (
    Boolean,
    Column,
    Integer,
    SmallInteger,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import ARRAY, INET, JSONB, TIMESTAMPTZ, UUID
from sqlalchemy.orm import DeclarativeBase
from sqlalchemy.sql import func


class AuditBase(DeclarativeBase):
    """Separate declarative base for the audit database."""


class ApiAuditLog(AuditBase):
    """
    Immutable audit record — one row per API request.

    Column descriptions
    -------------------
    id                  UUID primary key (auto-generated by PostgreSQL).
    timestamp_utc       Request completion time in UTC.
    client_id           OAuth 2.0 client_id extracted from the JWT.
    user_sub            Optional end-user subject from the JWT (Auth Code flow).
    method              HTTP method (GET, POST, …).
    endpoint            Normalised path with {param} placeholders.
    query_params        Raw query string as JSONB.
    request_body_hash   SHA-256 hex digest of the request body (POST/PUT/PATCH).
    scopes_used         Array of OAuth scopes present in the JWT.
    ip_origin           Client IP address (X-Forwarded-For aware).
    user_agent          User-Agent header value.
    http_status         HTTP response status code.
    response_time_ms    End-to-end latency in milliseconds.
    error_code          Application-level error code (if any).
    error_message       Short error description (if any).
    records_returned    Number of objects in the response body (if applicable).
    token_jti           JWT ID claim (UUID) for revocation tracking.
    geo_country         ISO 3166-1 alpha-3 country code (enriched offline).
    geo_city            Resolved city name (enriched offline).
    flagged             True when the record was flagged by an anomaly rule.
    flag_reason         Human-readable reason for the flag.
    """

    __tablename__ = "api_audit_log"
    __table_args__ = {"schema": "public"}

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )
    timestamp_utc = Column(TIMESTAMPTZ, nullable=False, server_default=func.now())
    client_id = Column(String(100), nullable=False)
    user_sub = Column(String(200), nullable=True)
    method = Column(String(10), nullable=False)
    endpoint = Column(String(500), nullable=False)
    query_params = Column(JSONB, nullable=True)
    request_body_hash = Column(String(64), nullable=True)
    scopes_used = Column(ARRAY(Text), nullable=True)
    ip_origin = Column(INET, nullable=False)
    user_agent = Column(String(500), nullable=True)
    http_status = Column(SmallInteger, nullable=False)
    response_time_ms = Column(Integer, nullable=False)
    error_code = Column(String(50), nullable=True)
    error_message = Column(String(500), nullable=True)
    records_returned = Column(Integer, nullable=True)
    token_jti = Column(UUID(as_uuid=True), nullable=True)
    geo_country = Column(String(3), nullable=True)
    geo_city = Column(String(100), nullable=True)
    flagged = Column(Boolean, nullable=False, default=False, server_default="false")
    flag_reason = Column(String(200), nullable=True)
