-- =============================================================================
-- UPC API Institucional — Initial Migration
-- File: 001_initial.sql
-- Database: upc_audit
--
-- Creates:
--   1. api_audit_log table (range-partitioned by timestamp_utc)
--   2. Default partition for all data
--   3. Four indexes for common query patterns
--   4. audit_resumen_diario materialized view
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- =============================================================================
-- 1. Main audit log table (partitioned)
-- =============================================================================

CREATE TABLE IF NOT EXISTS api_audit_log (
    id                  UUID            NOT NULL DEFAULT gen_random_uuid(),
    timestamp_utc       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    client_id           VARCHAR(100)    NOT NULL,
    user_sub            VARCHAR(200),
    method              VARCHAR(10)     NOT NULL,
    endpoint            VARCHAR(500)    NOT NULL,
    query_params        JSONB,
    request_body_hash   VARCHAR(64),
    scopes_used         TEXT[],
    ip_origin           INET            NOT NULL,
    user_agent          VARCHAR(500),
    http_status         SMALLINT        NOT NULL,
    response_time_ms    INTEGER         NOT NULL,
    error_code          VARCHAR(50),
    error_message       VARCHAR(500),
    records_returned    INTEGER,
    token_jti           UUID,
    geo_country         VARCHAR(3),
    geo_city            VARCHAR(100),
    flagged             BOOLEAN         NOT NULL DEFAULT FALSE,
    flag_reason         VARCHAR(200),
    PRIMARY KEY (id, timestamp_utc)
) PARTITION BY RANGE (timestamp_utc);

COMMENT ON TABLE api_audit_log IS
    'Immutable audit log — one row per API request. Partitioned by month.';

COMMENT ON COLUMN api_audit_log.id IS 'UUID primary key, generated by PostgreSQL';
COMMENT ON COLUMN api_audit_log.timestamp_utc IS 'Request completion timestamp (UTC)';
COMMENT ON COLUMN api_audit_log.client_id IS 'OAuth 2.0 client_id extracted from the JWT';
COMMENT ON COLUMN api_audit_log.user_sub IS 'End-user subject (Authorization Code flow only)';
COMMENT ON COLUMN api_audit_log.endpoint IS 'Normalised path with {param} placeholders';
COMMENT ON COLUMN api_audit_log.request_body_hash IS 'SHA-256 hex digest of POST/PUT/PATCH body';
COMMENT ON COLUMN api_audit_log.scopes_used IS 'OAuth 2.0 scopes present in the JWT';
COMMENT ON COLUMN api_audit_log.ip_origin IS 'Client IP (X-Forwarded-For aware)';
COMMENT ON COLUMN api_audit_log.token_jti IS 'JWT ID claim for revocation tracking';
COMMENT ON COLUMN api_audit_log.flagged IS 'True when flagged by an anomaly detection rule';

-- =============================================================================
-- 2. Partitions
-- =============================================================================

-- Default partition catches anything outside defined ranges
CREATE TABLE IF NOT EXISTS api_audit_log_default
    PARTITION OF api_audit_log DEFAULT;

-- 2024 partitions
CREATE TABLE IF NOT EXISTS api_audit_log_2024_01
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-01-01') TO ('2024-02-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_02
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-02-01') TO ('2024-03-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_03
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-03-01') TO ('2024-04-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_04
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-04-01') TO ('2024-05-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_05
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-05-01') TO ('2024-06-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_06
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-06-01') TO ('2024-07-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_07
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-07-01') TO ('2024-08-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_08
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-08-01') TO ('2024-09-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_09
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-09-01') TO ('2024-10-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_10
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-10-01') TO ('2024-11-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_11
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-11-01') TO ('2024-12-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2024_12
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2024-12-01') TO ('2025-01-01');

-- 2025 partitions
CREATE TABLE IF NOT EXISTS api_audit_log_2025_01
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_02
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_03
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-03-01') TO ('2025-04-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_04
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_05
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_06
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_07
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-07-01') TO ('2025-08-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_08
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-08-01') TO ('2025-09-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_09
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-09-01') TO ('2025-10-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_10
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_11
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2025_12
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');

-- 2026 partitions
CREATE TABLE IF NOT EXISTS api_audit_log_2026_01
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_02
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_03
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_04
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-04-01') TO ('2026-05-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_05
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_06
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_07
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_08
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_09
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_10
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_11
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');

CREATE TABLE IF NOT EXISTS api_audit_log_2026_12
    PARTITION OF api_audit_log
    FOR VALUES FROM ('2026-12-01') TO ('2027-01-01');

-- =============================================================================
-- 3. Indexes
-- =============================================================================

-- Index 1: Time-range scans (most common query pattern)
CREATE INDEX IF NOT EXISTS idx_audit_timestamp
    ON api_audit_log (timestamp_utc DESC);

-- Index 2: Per-client queries (security investigation, billing)
CREATE INDEX IF NOT EXISTS idx_audit_client_timestamp
    ON api_audit_log (client_id, timestamp_utc DESC);

-- Index 3: Endpoint performance analysis
CREATE INDEX IF NOT EXISTS idx_audit_endpoint_timestamp
    ON api_audit_log (endpoint, timestamp_utc DESC);

-- Index 4: Flagged / anomalous records
CREATE INDEX IF NOT EXISTS idx_audit_flagged
    ON api_audit_log (flagged, timestamp_utc DESC)
    WHERE flagged = TRUE;

-- =============================================================================
-- 4. Materialized view: daily summary
-- =============================================================================

CREATE MATERIALIZED VIEW IF NOT EXISTS audit_resumen_diario AS
SELECT
    DATE_TRUNC('day', timestamp_utc)::DATE          AS fecha,
    client_id,
    endpoint,
    COUNT(*)                                         AS total_requests,
    COUNT(*) FILTER (WHERE http_status >= 400
                       AND http_status < 500)        AS errores_4xx,
    COUNT(*) FILTER (WHERE http_status >= 500)       AS errores_5xx,
    ROUND(AVG(response_time_ms))                     AS avg_response_time_ms,
    PERCENTILE_CONT(0.95) WITHIN GROUP
        (ORDER BY response_time_ms)                  AS p95_response_time_ms,
    MAX(response_time_ms)                            AS max_response_time_ms,
    COUNT(DISTINCT ip_origin::TEXT)                  AS unique_ips,
    COUNT(*) FILTER (WHERE flagged = TRUE)           AS flagged_count
FROM api_audit_log
GROUP BY
    DATE_TRUNC('day', timestamp_utc)::DATE,
    client_id,
    endpoint
WITH DATA;

COMMENT ON MATERIALIZED VIEW audit_resumen_diario IS
    'Daily aggregated audit summary per client and endpoint. Refresh with REFRESH MATERIALIZED VIEW CONCURRENTLY audit_resumen_diario.';

-- Index for fast daily lookups on the materialized view
CREATE UNIQUE INDEX IF NOT EXISTS idx_resumen_diario_pk
    ON audit_resumen_diario (fecha, client_id, endpoint);

CREATE INDEX IF NOT EXISTS idx_resumen_diario_fecha
    ON audit_resumen_diario (fecha DESC);

-- =============================================================================
-- Refresh helper function
-- =============================================================================

CREATE OR REPLACE FUNCTION refresh_audit_resumen_diario()
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY audit_resumen_diario;
END;
$$;

COMMENT ON FUNCTION refresh_audit_resumen_diario() IS
    'Refresh the daily audit summary materialized view concurrently. Schedule via pg_cron or external scheduler.';
